parameters:
    locale: 'en'
    app.notifications.email_sender: arthuursimonian@gmail.com
    image_directory: '%kernel.project_dir%/public/images'

services:
    # default configuration for services in *this* file
    _defaults:
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
        autowire: true      # Automatically injects dependencies in your services.
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # le nom de votre service
    App\EventSubscriber\RegistrationNotifySubscriber:
        # le nom de la variable que l'on utilisera dans le service
        $sender: '%app.notifications.email_sender%'
      
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%image_directory%'    
        
    # le nom de votre service
    App\EventListener\ImageUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }  